import React, { useState, useEffect } from 'react';
import { StatCard, StatusBadge } from '../components/ui/UIComponents';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const HealthAnalytics = () => {
  const [workers, setWorkers] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedWorker, setSelectedWorker] = useState(null);
  const [scans, setScans] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const init = async () => {
      try {
        const res = await fetch('http://localhost:5000/api/workers');
        const data = await res.json();
        setWorkers(data);
        if (data.length > 0) setSelectedWorker(data[0]);
      } catch (err) {
        console.error('Data Sync Failure:', err);
      } finally {
        setIsLoading(false);
      }
    };
    init();
  }, []);

  useEffect(() => {
    if (selectedWorker) {
      fetchHistory(selectedWorker.id);
    }
  }, [selectedWorker]);

  const fetchHistory = async (workerId) => {
    try {
      const res = await fetch(`http://localhost:5000/api/scans/${workerId}`);
      const data = await res.json();
      setScans(data);
    } catch (err) {
      console.error('History Retrieval Failure:', err);
    }
  };

  const calculateAverages = () => {
    if (scans.length === 0) return { hr: 0, spo2: 0, status: 'N/A' };
    const sumHr = scans.reduce((acc, s) => acc + s.heartRate, 0);
    const sumSpo2 = scans.reduce((acc, s) => acc + s.spo2, 0);
    const avgHr = Math.round(sumHr / scans.length);
    const avgSpo2 = Math.round(sumSpo2 / scans.length);
    
    let status = 'Safe';
    if (avgHr > 100 || avgSpo2 < 94) status = 'Warning';
    if (avgHr > 115 || avgSpo2 < 92) status = 'Critical';
    
    return { hr: avgHr, spo2: avgSpo2, status };
  };

  const averages = calculateAverages();

  const downloadPDF = () => {
    if (!selectedWorker) return;
    const doc = new jsPDF();
    const adminData = localStorage.getItem('coalmine_admin');
    const admin = adminData ? JSON.parse(adminData) : { firstName: 'System', lastName: 'Admin' };

    // Header
    doc.setFontSize(22);
    doc.setTextColor(245, 179, 1);
    doc.text('COALSHIFT: HEALTH COMPLIANCE REPORT', 14, 22);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated By: ${admin.firstName} ${admin.lastName}`, 14, 30);
    doc.text(`Date: ${new Date().toLocaleString()}`, 14, 35);
    
    doc.setDrawColor(200);
    doc.line(14, 40, 196, 40);

    // Worker Details
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text('OPERATIVE PROFILE', 14, 52);
    doc.setFontSize(11);
    doc.text(`Name: ${selectedWorker.name}`, 14, 60);
    doc.text(`ID: ${selectedWorker.id}`, 14, 66);
    doc.text(`Department: ${selectedWorker.department}`, 14, 72);
    doc.text(`Biometric Template: Slot #${selectedWorker.fingerprintId}`, 14, 78);

    // Averages Box
    doc.setFillColor(245, 179, 1, 0.05);
    doc.rect(14, 85, 182, 35, 'F');
    doc.setFontSize(14);
    doc.text('WEEKLY ANALYSIS SUMMARY', 20, 95);
    doc.setFontSize(12);
    doc.text(`Average Heart Rate: ${averages.hr} BPM`, 20, 105);
    doc.text(`Average Blood Oxygen (SpO2): ${averages.spo2}%`, 20, 112);
    doc.text(`Safety Conclusion: ${averages.status.toUpperCase()}`, 120, 105);

    // Table of Records
    autoTable(doc, {
      startY: 130,
      head: [['Timestamp', 'Heart Rate', 'SpO2', 'Status']],
      body: scans.map(s => [
        new Date(s.timestamp).toLocaleString(),
        `${s.heartRate} BPM`,
        `${s.spo2}%`,
        s.status.toUpperCase()
      ]),
      headStyles: { fillColor: [245, 179, 1] },
      alternateRowStyles: { fillColor: [250, 250, 250] }
    });

    doc.save(`HealthReport_${selectedWorker.id}.pdf`);
  };

  const filteredWorkers = workers.filter(w => 
    w.name.toLowerCase().includes(searchTerm.toLowerCase()) || 
    w.id.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (isLoading) return <div style={{ color: 'var(--accent-primary)', padding: '4rem', textAlign: 'center' }}>Synchronizing Health Nodes... 📡</div>;

  return (
    <div className="animate-fade-in">
      <div className="page-header" style={{ marginBottom: '3rem' }}>
        <div>
          <h1 className="page-title">Health Analytics Hub</h1>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem', marginTop: '0.5rem' }}>
            Weekly averaged biometric telemetry and safety scoring.
          </p>
        </div>
        <button onClick={downloadPDF} className="btn btn-primary" style={{ height: 'fit-content' }}>
          📄 EXPORT PDF REPORT
        </button>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '320px 1fr', gap: '2.5rem' }}>
        {/* Sidebar Selection */}
        <div className="card glass" style={{ height: 'fit-content' }}>
          <h3 style={{ fontSize: '0.9rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: '1.5rem', letterSpacing: '0.1em' }}>Select Operative</h3>
          
          {/* Worker Search Bar */}
          <div style={{ marginBottom: '1.5rem', position: 'relative' }}>
            <input 
              type="text" 
              placeholder="Search by name or ID..." 
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              style={{
                width: '100%',
                padding: '0.75rem 1rem',
                background: 'rgba(255,255,255,0.03)',
                border: '1.5px solid var(--border-color)',
                borderRadius: '8px',
                color: '#fff',
                fontSize: '0.85rem',
                outline: 'none',
                transition: 'border-color 0.2s ease'
              }}
              onFocus={(e) => e.target.style.borderColor = 'var(--accent-primary)'}
              onBlur={(e) => e.target.style.borderColor = 'var(--border-color)'}
            />
            <span style={{ position: 'absolute', right: '1rem', top: '50%', transform: 'translateY(-50%)', opacity: 0.5 }}>🔍</span>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', maxHeight: '500px', overflowY: 'auto', paddingRight: '0.5rem' }}>
            {filteredWorkers.length > 0 ? (
              filteredWorkers.map(w => (
                <div 
                  key={w._id}
                  onClick={() => setSelectedWorker(w)}
                  style={{ 
                    padding: '1rem', 
                    background: selectedWorker?.id === w.id ? 'rgba(245, 179, 1, 0.1)' : 'rgba(255,255,255,0.02)',
                    border: `1.5px solid ${selectedWorker?.id === w.id ? 'var(--accent-primary)' : 'transparent'}`,
                    borderRadius: 'var(--radius-md)',
                    cursor: 'pointer',
                    transition: 'all 0.2s ease'
                  }}
                >
                  <div style={{ fontWeight: 'bold', fontSize: '0.9rem' }}>{w.name}</div>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>ID: {w.id}</div>
                </div>
              ))
            ) : (
              <div style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-muted)', fontSize: '0.85rem', background: 'rgba(255,255,255,0.01)', borderRadius: '8px', border: '1px dashed var(--border-color)' }}>
                No operatives found matching "{searchTerm}"
              </div>
            )}
          </div>
        </div>

        {/* Analytics Display */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
          {selectedWorker ? (
            <>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1.5rem' }}>
                <div className="card" style={{ textAlign: 'center', borderBottom: '4px solid var(--accent-primary)' }}>
                   <div style={{ color: 'var(--text-muted)', fontSize: '0.8rem', marginBottom: '1rem' }}>WEEKLY AVG HEART RATE</div>
                   <div style={{ fontSize: '2.5rem', fontWeight: '900', color: 'var(--accent-primary)' }}>{averages.hr} <span style={{ fontSize: '1rem' }}>BPM</span></div>
                </div>
                <div className="card" style={{ textAlign: 'center', borderBottom: '4px solid var(--info)' }}>
                   <div style={{ color: 'var(--text-muted)', fontSize: '0.8rem', marginBottom: '1rem' }}>WEEKLY AVG SPO2</div>
                   <div style={{ fontSize: '2.5rem', fontWeight: '900', color: 'var(--info)' }}>{averages.spo2} <span style={{ fontSize: '1rem' }}>%</span></div>
                </div>
                <div className="card" style={{ textAlign: 'center', borderBottom: `4px solid var(--${averages.status.toLowerCase()})` }}>
                   <div style={{ color: 'var(--text-muted)', fontSize: '0.8rem', marginBottom: '1rem' }}>SAFETY STATUS</div>
                   <div style={{ fontSize: '1.8rem', fontWeight: '900', color: `var(--${averages.status.toLowerCase()})` }}>{averages.status.toUpperCase()}</div>
                </div>
              </div>

              <div className="card glass">
                 <h3 style={{ marginBottom: '2rem', fontSize: '1.1rem', fontWeight: '800' }}>Biometric Record History (Last 50 Scans)</h3>
                 {scans.length > 0 ? (
                   <table className="data-table">
                     <thead>
                       <tr>
                         <th>Timestamp</th>
                         <th>Heart Rate</th>
                         <th>Oxygen Saturation</th>
                         <th>Health Grade</th>
                       </tr>
                     </thead>
                     <tbody>
                       {scans.map(s => (
                         <tr key={s._id}>
                           <td>{new Date(s.timestamp).toLocaleString()}</td>
                           <td style={{ fontWeight: 'bold' }}>{s.heartRate} BPM</td>
                           <td style={{ fontWeight: 'bold' }}>{s.spo2}%</td>
                           <td><StatusBadge status={s.status} /></td>
                         </tr>
                       ))}
                     </tbody>
                   </table>
                 ) : (
                   <div style={{ padding: '4rem', textAlign: 'center', color: 'var(--text-muted)', border: '1px dashed var(--border-color)', borderRadius: '12px' }}>
                     No historical health data found for this operative. 🩺
                   </div>
                 )}
              </div>
            </>
          ) : (
            <div className="card glass" style={{ height: '400px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-muted)' }}>
              Select a worker from the sidebar to view detailed health averages.
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default HealthAnalytics;
